version: "3.9"

volumes:
  postgresdata: {}

services:
  postgres:
    image: "postgres:14.3-alpine"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
  app:
    build: .
    command: python main.py
    depends_on:
      - postgres
